name: Build

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency: 
  group: "build"
  cancel-in-progress: true

permissions:
  contents: write   

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'  # Catch all markdown files
      - 'docs/**'  # Ignore documentation changes
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@4
        with:
          ref: "builds"
          path: "builds"
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle  # Enable Gradle caching

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force origin builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
